export enum RestStatus {
  SUCCESS = '200',
  BAD_REQUEST = '400',
  UNAUTHORIZED = '401',
  FORBIDDEN = '403',
  NOT_FOUND = '404',
  INTERNAL_SERVER_ERROR = '500',
  UNKNOWN = '9999',
}

export enum WarningCode {
  ACTIVITY_REVIEW_HISTORY_NOT_FOUND = '9203',
  NO_LAST_APPROVED_ACTIVITY_REVIEW_HISTORY = '9205',
  TAG_REVIEW_HISTORY_NOT_FOUND = '9303',
  NO_LAST_APPROVED_TAG_REVIEW_HISTORY = '9308',
  SCHEDULE_REVIEW_HISTORY_NOT_FOUND = '9502',
}