import { ScheduleReviewHistory } from "@api/models/schedule-activity.model";

export const ScheduleReviewHistoryMock: Array<ScheduleReviewHistory> = [
   {
      "historyId": "h123456",
      "version": "uuid-zzzz",
      "referenceId": "uuid-1",
      "groupId": 1,
      "time": "2023-07-18 10:30:00",
      "title": "建立排程管理送審",
      "detail": "送程主管",
      "type": "建立活動",
      "reviewStatus": "reviewing",
      "reviewer": "John Doe",
      "reviewComment": "排程管理通過",
      "reviewTime": "2023-07-03 15:30:00",
      "jobName": "Job Name",
      "executionFrequency": "Daily",
      "frequencyTime": "00:00",
      "filePath": "C://",
      "creationTime": "2023-07-20 10:00:00",
      "modificationTime": "2023-07-20 12:30:00",
      "status": "disabled",
      "newActivitySetting": [
         {
            "activityId": "2498e0bf-2289-4fd9-a037-04a6888a9399",
            "version": "uuid-zzzz",
            "activityName": "新商品快閃體驗活動",
            "activityDescription": "新商品快閃體驗活動",
            "department": "所屬單位",
            "owner": "負責人",
            "filterOptions": "true",
            "listLimit": 100,
            "status": "active",
            "reviewStatus": "approved",
            "startDate": "2023-07-01",
            "endDate": "2023-07-10",
            "createTime": "2023-07-03 15:30:00",
            "modificationTime": "2023-07-03 15:30:00",
            "scheduleSettings": "daily",
            "batchUpdateTime": "2023-07-03 12:00:00",
            "batchTime": null,
            "batchResult": null
         },
         {
            "activityId": "abcdefg123456",
            "version": "uuid-zzzz",
            "activityName": "女王節活動",
            "activityDescription": "女王節活動 EDM 名單",
            "department": "所屬單位",
            "owner": "負責人",
            "filterOptions": "true",
            "listLimit": 100,
            "status": "active",
            "reviewStatus": "approved",
            "startDate": "2023-07-01",
            "endDate": "2023-07-10",
            "createTime": "2023-07-03 15:30:00",
            "modificationTime": "2023-07-03 15:30:00",
            "scheduleSettings": "daily",
            "batchUpdateTime": "2023-07-03 12:00:00",
            "batchTime": null,
            "batchResult": null
         }
      ],
      "lastActivitySetting": [
         {
            "activityId": "abcdefg123456",
            "version": "uuid-zzzz",
            "activityName": "女王節活動",
            "activityDescription": "女王節活動 EDM 名單",
            "department": "所屬單位",
            "owner": "負責人",
            "filterOptions": "true",
            "listLimit": 100,
            "status": "active",
            "reviewStatus": "reviewing",
            "startDate": "2023-07-01",
            "endDate": "2023-07-10",
            "createTime": "2023-07-03 15:30:00",
            "modificationTime": "2023-07-03 15:30:00",
            "scheduleSettings": "daily",
            "batchUpdateTime": "2023-07-03 12:00:00",
            "batchTime": null,
            "batchResult": null
         },
         {
            "activityId": "f32510d7-225b-4c07-82a6-1292a7ec55c7",
            "version": "uuid-zzzz",
            "activityName": "七夕情人節活動",
            "activityDescription": "-",
            "department": "所屬單位",
            "owner": "負責人",
            "filterOptions": "true",
            "listLimit": 100,
            "status": "active",
            "reviewStatus": "reviewing",
            "startDate": "2023-07-01",
            "endDate": "2023-07-10",
            "createTime": "2023-07-03 15:30:00",
            "modificationTime": "2023-07-03 15:30:00",
            "scheduleSettings": "daily",
            "batchUpdateTime": "2023-07-03 12:00:00",
            "batchTime": null,
            "batchResult": null
         }
      ],
      "scheduleReviewHistoryAud": [
         {
            "historyId": "h123457",
            "version": "uuid-zzzz",
            "referenceId": "uuid-1",
            "groupId": 1,
            "time": "2023-08-09T17:41:36",
            "title": "建立排程管理送審",
            "detail": "送程主管",
            "type": "建立活動",
            "reviewStatus": "approved",
            "reviewer": "John Doe",
            "reviewComment": "排程管理通過",
            "reviewTime": "2023-08-21 13:51:52",
            "jobName": "Job Name",
            "executionFrequency": "daily",
            "frequencyTime": "00:00",
            "filePath": "/file/path/",
            "creationTime": "2023-08-09T17:41:36",
            "modificationTime": "2023-08-09T17:41:36",
            "status": "enabled"
         },
         {
            "historyId": "7a128341-e43b-41fb-a223-cc0fac367aa3",
            "version": "8d209a11-51fd-4ec9-9f81-83f4b1fa8e86",
            "referenceId": "uuid-1",
            "groupId": 3,
            "time": "2023-08-21T16:39:08",
            "title": "建立名單送審",
            "detail": "送程主管",
            "type": "建立排程",
            "reviewStatus": "reviewing",
            "reviewer": null,
            "reviewComment": null,
            "reviewTime": null,
            "jobName": "Job Name",
            "executionFrequency": "daily",
            "frequencyTime": "00:00",
            "filePath": "/file/path/",
            "creationTime": null,
            "modificationTime": null,
            "status": "enabled",
         },
         {
            "historyId": "54266804-ce7e-4db7-b920-47d74e15277a",
            "version": "530a99ce-0317-489e-bf4c-8c239d45def9",
            "referenceId": "uuid-1",
            "groupId": 4,
            "time": "2023-08-21T16:46:37",
            "title": "建立名單送審",
            "detail": "送程主管",
            "type": "建立排程",
            "reviewStatus": "reviewing",
            "reviewer": null,
            "reviewComment": null,
            "reviewTime": null,
            "jobName": "Job Name",
            "executionFrequency": "daily",
            "frequencyTime": "00:00",
            "filePath": "/file/path/",
            "creationTime": null,
            "modificationTime": null,
            "status": "enabled",
         },
         {
            "historyId": "32a1f8c7-1abf-4d17-bfc1-b4c77ed38e5e",
            "version": "53a0c224-40ce-42ad-8973-44caaa66c469",
            "referenceId": "uuid-1",
            "groupId": 5,
            "time": "2023-08-21T16:47:05",
            "title": "建立名單送審",
            "detail": "送程主管",
            "type": "建立排程",
            "reviewStatus": "reviewing",
            "reviewer": null,
            "reviewComment": null,
            "reviewTime": null,
            "jobName": "Job Name",
            "executionFrequency": "daily",
            "frequencyTime": "00:00",
            "filePath": "/file/path/",
            "creationTime": null,
            "modificationTime": null,
            "status": "rejected",
         }
      ]
   },
   {
      "historyId": "h123457",
      "version": "uuid-zzzz",
      "referenceId": "uuid-1",
      "groupId": 2,
      "time": "2023-07-01 10:30:00",
      "title": "編輯排程管理送審",
      "detail": "送程主管",
      "type": "編輯活動",
      "reviewStatus": "approved",
      "reviewer": "老王",
      "reviewComment": "排程編輯管理通過",
      "reviewTime": "2023-07-03 15:30:00",
      "jobName": "Job",
      "executionFrequency": "monthly",
      "frequencyTime": "13:30:00",
      "filePath": "/file/path/",
      "creationTime": "2023-07-20 10:00:00",
      "modificationTime": "2023-07-20 12:30:00",
      "status": "enabled",
      "newActivitySetting": [
         {
            "activityId": "abcdefg123456",
            "version": "uuid-zzzz",
            "activityName": "女王節活動",
            "activityDescription": "女王節活動 EDM 名單",
            "department": "所屬單位",
            "owner": "負責人",
            "filterOptions": "true",
            "listLimit": 100,
            "status": "active",
            "reviewStatus": "approved",
            "startDate": "2023-07-01",
            "endDate": "2023-07-10",
            "createTime": "2023-07-03 15:30:00",
            "modificationTime": "2023-07-03 15:30:00",
            "scheduleSettings": "daily",
            "batchUpdateTime": "2023-07-03 12:00:00",
            "batchTime": null,
            "batchResult": null
         }
      ],
      "lastActivitySetting": [
         {
            "activityId": "f32510d7-225b-4c07-82a6-1292a7ec55c7",
            "version": "uuid-zzzz",
            "activityName": "七夕情人節活動",
            "activityDescription": "-",
            "department": "所屬單位",
            "owner": "負責人",
            "filterOptions": "true",
            "listLimit": 100,
            "status": "active",
            "reviewStatus": "approved",
            "startDate": "2023-07-01",
            "endDate": "2023-07-10",
            "createTime": "2023-07-03 15:30:00",
            "modificationTime": "2023-07-03 15:30:00",
            "scheduleSettings": "daily",
            "batchUpdateTime": "2023-07-03 12:00:00",
            "batchTime": "2023-07-13 12:00:00",
            "batchResult": "success"
         }
      ]
   },
   {
      "historyId": "h123458",
      "version": "uuid-zzzz",
      "referenceId": "uuid-1",
      "groupId": 1,
      "time": "2023-07-01 10:30:00",
      "title": "編輯排程管理送審",
      "detail": "送程主管",
      "type": "編輯活動",
      "reviewStatus": "rejected",
      "reviewer": "Christina",
      "reviewComment": "排程編輯管理通過",
      "reviewTime": "2023-07-03 15:30:00",
      "jobName": "每週EDM排程",
      "executionFrequency": "weekly",
      "frequencyTime": "10:00",
      "filePath": "/file/path/",
      "creationTime": "2023-07-20 10:00:00",
      "modificationTime": "2023-07-20 12:30:00",
      "status": "enabled",
      "newActivitySetting": [
         {
            "activityId": "abcdefg123456",
            "version": "uuid-zzzz",
            "activityName": "女王節活動",
            "activityDescription": "女王節活動 EDM 名單",
            "department": "所屬單位",
            "owner": "負責人",
            "filterOptions": "true",
            "listLimit": 100,
            "status": "active",
            "reviewStatus": "approved",
            "startDate": "2023-07-01",
            "endDate": "2023-07-10",
            "createTime": "2023-07-03 15:30:00",
            "modificationTime": "2023-07-03 15:30:00",
            "scheduleSettings": "daily",
            "batchUpdateTime": "2023-07-03 12:00:00",
            "batchTime": "2023-07-03 12:00:00",
            "batchResult": "success"
         },
         {
            "activityId": "2498e0bf-2289-4fd9-a037-04a6888a9399",
            "version": "uuid-zzzz",
            "activityName": "新商品快閃體驗活動",
            "activityDescription": "新商品快閃體驗活動",
            "department": "所屬單位",
            "owner": "負責人",
            "filterOptions": "true",
            "listLimit": 100,
            "status": "active",
            "reviewStatus": "reviewing",
            "startDate": "2023-07-01",
            "endDate": "2023-07-10",
            "createTime": "2023-07-03 15:30:00",
            "modificationTime": "2023-07-03 15:30:00",
            "scheduleSettings": "daily",
            "batchUpdateTime": "2023-07-03 12:00:00",
            "batchTime": "2023-07-13 12:00:00",
            "batchResult": "success",
         },
         {
            "activityId": "90b010ba-bd4b-480a-a0c7-3a35096f2ed8",
            "version": "uuid-zzzz",
            "activityName": "LINE TECHPULSE 2023",
            "activityDescription": "LINE TECHPULSE 2023",
            "department": "所屬單位",
            "owner": "負責人",
            "filterOptions": "true",
            "listLimit": 100,
            "status": "active",
            "reviewStatus": "reviewing",
            "startDate": "2023-07-01",
            "endDate": "2023-07-10",
            "createTime": "2023-07-03 15:30:00",
            "modificationTime": "2023-07-03 15:30:00",
            "scheduleSettings": "daily",
            "batchUpdateTime": "2023-07-03 12:00:00",
            "batchTime": null,
            "batchResult": null
         },
      ],
      "lastActivitySetting": [
         {
            "activityId": "abcdefg123456",
            "version": "uuid-zzzz",
            "activityName": "女王節活動",
            "activityDescription": "女王節活動 EDM 名單",
            "department": "所屬單位",
            "owner": "負責人",
            "filterOptions": "true",
            "listLimit": 100,
            "status": "active",
            "reviewStatus": "approved",
            "startDate": "2023-07-01",
            "endDate": "2023-07-10",
            "createTime": "2023-07-03 15:30:00",
            "modificationTime": "2023-07-03 15:30:00",
            "scheduleSettings": "daily",
            "batchUpdateTime": "2023-07-03 12:00:00",
            "batchTime": null,
            "batchResult": null
         }
      ]
   },
]
