import { TagReviewHistory } from "@api/models/tag-manage.model";

export const TagReviewListMock: Array<TagReviewHistory> = [
  {
    historyId: "hh123461",
    referenceId: "cccccc123456",
    groupId: 3,
    time: "2023-07-01 09:00:00",
    title: "修改",
    detail: "排程設定",
    type: "修改標籤",
    reviewStatus: "rejected",
    reviewer: "林XX",
    reviewComment: "退回",
    tagName: "近一個月金申金額",
    tagDescription: "標籤說明標說明標籤說明",
    tagType: "normal",
    department: "數位金融處",
    owner: "林XX",
    modificationTime: "2023-07-02 15:30:00",
    status: "active",
    startDate: "2023-07-01",
    endDate: "2023-07-10",
    conditionSettingMethod: "條件設定方式",
    conditionSettingQuery: "條件設定語法",
    tagDimension: "標籤構面",
    tagSubDimension: "標籤子構面",
    scheduleSettings: "排成設定",
    uploadType: "monthly",
    filePath: "上傳檔案路徑"
  },
  {
    historyId: "hh123459",
    referenceId: "cccccc123456",
    groupId: 2,
    time: "2023-07-01 09:00:00",
    title: "修改",
    detail: "上線人數",
    type: "修改標籤",
    reviewStatus: "approved",
    reviewer: "林XX",
    reviewComment: "",
    tagName: "已婚",
    tagDescription: "標籤說明",
    tagType: "document",
    department: "數位金融處",
    owner: "武XX",
    modificationTime: "2023-07-03 15:30:00",
    status: "active",
    startDate: "2023-06-01",
    endDate: "2023-08-30",
    conditionSettingMethod: "條件設定方式",
    conditionSettingQuery: "條件設定語法",
    tagDimension: "標籤構面",
    tagSubDimension: "標籤子構面",
    scheduleSettings: "daily",
    uploadType: "名單上傳類型",
    filePath: "上傳檔案路徑"
  },
  {
    historyId: "hh123460",
    referenceId: "cccccc123456",
    groupId: 1,
    time: "2023-07-01 09:00:00",
    title: "審核",
    detail: "同意",
    type: "建立標籤",
    reviewStatus: "reviewing",
    reviewer: "王XX",
    reviewComment: "",
    tagName: "非信用卡客戶",
    tagDescription: "標籤說明標說明標籤說明",
    tagType: "normal",
    department: "信用卡暨支付處",
    owner: "馬XX",
    modificationTime: "2023-07-03 15:30:00",
    status: "active",
    startDate: "2023-06-01",
    endDate: "2023-08-30",
    conditionSettingMethod: "條件設定方式",
    conditionSettingQuery: "條件設定語法",
    tagDimension: "標籤構面",
    tagSubDimension: "標籤子構面",
    scheduleSettings: "daily",
    uploadType: "名單上傳類型",
    filePath: "上傳檔案路徑"
  },
]
